GET http://localhost:8080/api/tickets/
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2IzODIyOWUyMTA4MTcyODFkNDY0MTgiLCJuYW1lIjoianVhbiIsImlhdCI6MTY3MjcwODY0OSwiZXhwIjoxNjcyNzk1MDQ5fQ.WUySmUTgPU0mincIBtjzdQQWzrh1tBgiUS8okfYYd-4